version: '3.3'

volumes:
  postgres_data:

services:

  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../block/block/.env

  backend:
    build: ../block/
    depends_on:
      - db
    env_file:
      - ../block/block/.env