# Generated by Django 4.2.4 on 2023-08-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(default=14, unique=True),
            preserve_default=False,
        ),
    ]
