# Generated by Django 4.2.4 on 2023-08-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
    ]
